# Generated by Django 5.1.7 on 2025-04-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_user_managers_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
