# Generated by Django 5.1.7 on 2025-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_user_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='division',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Practical', 'Practical')], default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(choices=[(1, 'FY'), (2, 'SY'), (3, 'TY'), (4, 'BE')], default=2),
            preserve_default=False,
        ),
    ]
